t3t:
  feignClient:
    url: ${feignClientUrl}

spring:
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache: true
  devtools:
    restart:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eurekaServiceUrlDefaultZone}
